// ignore_for_file: camel_case_types

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
@ffi.DefaultAsset('package:dart_zvec/src/bindings.dart')
library;

import 'dart:ffi' as ffi;

@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<zvec_collection_t>)>(
  symbol: 'zvec_collection_close',
)
external int _zvec_collection_close(ffi.Pointer<zvec_collection_t> collection);

zvec_error_code_t zvec_collection_close(
  ffi.Pointer<zvec_collection_t> collection,
) => zvec_error_code_t.fromValue(_zvec_collection_close(collection));

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<zvec_collection_schema_t>,
    ffi.Pointer<zvec_collection_options_t>,
    ffi.Pointer<ffi.Pointer<zvec_collection_t>>,
  )
>(symbol: 'zvec_collection_create_and_open')
external int _zvec_collection_create_and_open(
  ffi.Pointer<ffi.Char> path,
  ffi.Pointer<zvec_collection_schema_t> schema,
  ffi.Pointer<zvec_collection_options_t> options,
  ffi.Pointer<ffi.Pointer<zvec_collection_t>> collection,
);

zvec_error_code_t zvec_collection_create_and_open(
  ffi.Pointer<ffi.Char> path,
  ffi.Pointer<zvec_collection_schema_t> schema,
  ffi.Pointer<zvec_collection_options_t> options,
  ffi.Pointer<ffi.Pointer<zvec_collection_t>> collection,
) => zvec_error_code_t.fromValue(
  _zvec_collection_create_and_open(path, schema, options, collection),
);

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<zvec_collection_t>,
    ffi.Pointer<ffi.Pointer<zvec_doc_t>>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
    ffi.Pointer<ffi.Size>,
  )
>(symbol: 'zvec_collection_insert')
external int _zvec_collection_insert(
  ffi.Pointer<zvec_collection_t> collection,
  ffi.Pointer<ffi.Pointer<zvec_doc_t>> docs,
  int doc_count,
  ffi.Pointer<ffi.Size> success_count,
  ffi.Pointer<ffi.Size> error_count,
);

zvec_error_code_t zvec_collection_insert(
  ffi.Pointer<zvec_collection_t> collection,
  ffi.Pointer<ffi.Pointer<zvec_doc_t>> docs,
  int doc_count,
  ffi.Pointer<ffi.Size> success_count,
  ffi.Pointer<ffi.Size> error_count,
) => zvec_error_code_t.fromValue(
  _zvec_collection_insert(
    collection,
    docs,
    doc_count,
    success_count,
    error_count,
  ),
);

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<zvec_collection_options_t>,
    ffi.Pointer<ffi.Pointer<zvec_collection_t>>,
  )
>(symbol: 'zvec_collection_open')
external int _zvec_collection_open(
  ffi.Pointer<ffi.Char> path,
  ffi.Pointer<zvec_collection_options_t> options,
  ffi.Pointer<ffi.Pointer<zvec_collection_t>> collection,
);

zvec_error_code_t zvec_collection_open(
  ffi.Pointer<ffi.Char> path,
  ffi.Pointer<zvec_collection_options_t> options,
  ffi.Pointer<ffi.Pointer<zvec_collection_t>> collection,
) => zvec_error_code_t.fromValue(
  _zvec_collection_open(path, options, collection),
);

@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<zvec_collection_t>)>(
  symbol: 'zvec_collection_optimize',
)
external int _zvec_collection_optimize(
  ffi.Pointer<zvec_collection_t> collection,
);

zvec_error_code_t zvec_collection_optimize(
  ffi.Pointer<zvec_collection_t> collection,
) => zvec_error_code_t.fromValue(_zvec_collection_optimize(collection));

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<zvec_collection_t>,
    ffi.Pointer<zvec_vector_query_t>,
    ffi.Pointer<ffi.Pointer<ffi.Pointer<zvec_doc_t>>>,
    ffi.Pointer<ffi.Size>,
  )
>(symbol: 'zvec_collection_query')
external int _zvec_collection_query(
  ffi.Pointer<zvec_collection_t> collection,
  ffi.Pointer<zvec_vector_query_t> query,
  ffi.Pointer<ffi.Pointer<ffi.Pointer<zvec_doc_t>>> results,
  ffi.Pointer<ffi.Size> result_count,
);

zvec_error_code_t zvec_collection_query(
  ffi.Pointer<zvec_collection_t> collection,
  ffi.Pointer<zvec_vector_query_t> query,
  ffi.Pointer<ffi.Pointer<ffi.Pointer<zvec_doc_t>>> results,
  ffi.Pointer<ffi.Size> result_count,
) => zvec_error_code_t.fromValue(
  _zvec_collection_query(collection, query, results, result_count),
);

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<zvec_collection_schema_t>,
    ffi.Pointer<zvec_field_schema_t>,
  )
>(symbol: 'zvec_collection_schema_add_field')
external int _zvec_collection_schema_add_field(
  ffi.Pointer<zvec_collection_schema_t> schema,
  ffi.Pointer<zvec_field_schema_t> field,
);

zvec_error_code_t zvec_collection_schema_add_field(
  ffi.Pointer<zvec_collection_schema_t> schema,
  ffi.Pointer<zvec_field_schema_t> field,
) => zvec_error_code_t.fromValue(
  _zvec_collection_schema_add_field(schema, field),
);

@ffi.Native<
  ffi.Pointer<zvec_collection_schema_t> Function(ffi.Pointer<ffi.Char>)
>()
external ffi.Pointer<zvec_collection_schema_t> zvec_collection_schema_create(
  ffi.Pointer<ffi.Char> name,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<zvec_collection_schema_t>)>()
external void zvec_collection_schema_destroy(
  ffi.Pointer<zvec_collection_schema_t> schema,
);

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<zvec_doc_t>,
    ffi.Pointer<ffi.Char>,
    ffi.Uint32,
    ffi.Pointer<ffi.Void>,
    ffi.Size,
  )
>(symbol: 'zvec_doc_add_field_by_value')
external int _zvec_doc_add_field_by_value(
  ffi.Pointer<zvec_doc_t> doc,
  ffi.Pointer<ffi.Char> field_name,
  int data_type,
  ffi.Pointer<ffi.Void> value,
  int value_size,
);

zvec_error_code_t zvec_doc_add_field_by_value(
  ffi.Pointer<zvec_doc_t> doc,
  ffi.Pointer<ffi.Char> field_name,
  int data_type,
  ffi.Pointer<ffi.Void> value,
  int value_size,
) => zvec_error_code_t.fromValue(
  _zvec_doc_add_field_by_value(doc, field_name, data_type, value, value_size),
);

@ffi.Native<ffi.Pointer<zvec_doc_t> Function()>()
external ffi.Pointer<zvec_doc_t> zvec_doc_create();

@ffi.Native<ffi.Void Function(ffi.Pointer<zvec_doc_t>)>()
external void zvec_doc_destroy(ffi.Pointer<zvec_doc_t> doc);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<zvec_doc_t>)>()
external ffi.Pointer<ffi.Char> zvec_doc_get_pk_pointer(
  ffi.Pointer<zvec_doc_t> doc,
);

@ffi.Native<ffi.Float Function(ffi.Pointer<zvec_doc_t>)>()
external double zvec_doc_get_score(ffi.Pointer<zvec_doc_t> doc);

@ffi.Native<ffi.Void Function(ffi.Pointer<zvec_doc_t>, ffi.Pointer<ffi.Char>)>()
external void zvec_doc_set_pk(
  ffi.Pointer<zvec_doc_t> doc,
  ffi.Pointer<ffi.Char> pk,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Pointer<zvec_doc_t>>, ffi.Size)>()
external void zvec_docs_free(
  ffi.Pointer<ffi.Pointer<zvec_doc_t>> documents,
  int count,
);

@ffi.Native<
  ffi.Pointer<zvec_field_schema_t> Function(
    ffi.Pointer<ffi.Char>,
    ffi.Uint32,
    ffi.Bool,
    ffi.Uint32,
  )
>()
external ffi.Pointer<zvec_field_schema_t> zvec_field_schema_create(
  ffi.Pointer<ffi.Char> name,
  int data_type,
  bool nullable,
  int dimension,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<zvec_field_schema_t>)>()
external void zvec_field_schema_destroy(
  ffi.Pointer<zvec_field_schema_t> schema,
);

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<zvec_field_schema_t>,
    ffi.Pointer<zvec_index_params_t>,
  )
>(symbol: 'zvec_field_schema_set_index_params')
external int _zvec_field_schema_set_index_params(
  ffi.Pointer<zvec_field_schema_t> schema,
  ffi.Pointer<zvec_index_params_t> index_params,
);

zvec_error_code_t zvec_field_schema_set_index_params(
  ffi.Pointer<zvec_field_schema_t> schema,
  ffi.Pointer<zvec_index_params_t> index_params,
) => zvec_error_code_t.fromValue(
  _zvec_field_schema_set_index_params(schema, index_params),
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void zvec_free(ffi.Pointer<ffi.Void> ptr);

@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<ffi.Pointer<ffi.Char>>)>(
  symbol: 'zvec_get_last_error',
)
external int _zvec_get_last_error(ffi.Pointer<ffi.Pointer<ffi.Char>> error_msg);

zvec_error_code_t zvec_get_last_error(
  ffi.Pointer<ffi.Pointer<ffi.Char>> error_msg,
) => zvec_error_code_t.fromValue(_zvec_get_last_error(error_msg));

@ffi.Native<ffi.Pointer<ffi.Char> Function()>()
external ffi.Pointer<ffi.Char> zvec_get_version();

@ffi.Native<ffi.Pointer<zvec_index_params_t> Function(ffi.Uint32)>()
external ffi.Pointer<zvec_index_params_t> zvec_index_params_create(
  int index_type,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<zvec_index_params_t>)>()
external void zvec_index_params_destroy(
  ffi.Pointer<zvec_index_params_t> params,
);

@ffi.Native<
  ffi.UnsignedInt Function(ffi.Pointer<zvec_index_params_t>, ffi.Int, ffi.Int)
>(symbol: 'zvec_index_params_set_hnsw_params')
external int _zvec_index_params_set_hnsw_params(
  ffi.Pointer<zvec_index_params_t> params,
  int m,
  int ef_construction,
);

zvec_error_code_t zvec_index_params_set_hnsw_params(
  ffi.Pointer<zvec_index_params_t> params,
  int m,
  int ef_construction,
) => zvec_error_code_t.fromValue(
  _zvec_index_params_set_hnsw_params(params, m, ef_construction),
);

@ffi.Native<
  ffi.UnsignedInt Function(ffi.Pointer<zvec_index_params_t>, ffi.Uint32)
>(symbol: 'zvec_index_params_set_metric_type')
external int _zvec_index_params_set_metric_type(
  ffi.Pointer<zvec_index_params_t> params,
  int metric_type,
);

zvec_error_code_t zvec_index_params_set_metric_type(
  ffi.Pointer<zvec_index_params_t> params,
  int metric_type,
) => zvec_error_code_t.fromValue(
  _zvec_index_params_set_metric_type(params, metric_type),
);

@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<zvec_config_data_t>)>(
  symbol: 'zvec_initialize',
)
external int _zvec_initialize(ffi.Pointer<zvec_config_data_t> config);

zvec_error_code_t zvec_initialize(ffi.Pointer<zvec_config_data_t> config) =>
    zvec_error_code_t.fromValue(_zvec_initialize(config));

@ffi.Native<ffi.Bool Function()>()
external bool zvec_is_initialized();

@ffi.Native<ffi.UnsignedInt Function()>(symbol: 'zvec_shutdown')
external int _zvec_shutdown();

zvec_error_code_t zvec_shutdown() =>
    zvec_error_code_t.fromValue(_zvec_shutdown());

@ffi.Native<ffi.Pointer<zvec_vector_query_t> Function()>()
external ffi.Pointer<zvec_vector_query_t> zvec_vector_query_create();

@ffi.Native<ffi.Void Function(ffi.Pointer<zvec_vector_query_t>)>()
external void zvec_vector_query_destroy(ffi.Pointer<zvec_vector_query_t> query);

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<zvec_vector_query_t>,
    ffi.Pointer<ffi.Char>,
  )
>(symbol: 'zvec_vector_query_set_field_name')
external int _zvec_vector_query_set_field_name(
  ffi.Pointer<zvec_vector_query_t> query,
  ffi.Pointer<ffi.Char> field_name,
);

zvec_error_code_t zvec_vector_query_set_field_name(
  ffi.Pointer<zvec_vector_query_t> query,
  ffi.Pointer<ffi.Char> field_name,
) => zvec_error_code_t.fromValue(
  _zvec_vector_query_set_field_name(query, field_name),
);

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<zvec_vector_query_t>,
    ffi.Pointer<ffi.Void>,
    ffi.Size,
  )
>(symbol: 'zvec_vector_query_set_query_vector')
external int _zvec_vector_query_set_query_vector(
  ffi.Pointer<zvec_vector_query_t> query,
  ffi.Pointer<ffi.Void> data,
  int size,
);

zvec_error_code_t zvec_vector_query_set_query_vector(
  ffi.Pointer<zvec_vector_query_t> query,
  ffi.Pointer<ffi.Void> data,
  int size,
) => zvec_error_code_t.fromValue(
  _zvec_vector_query_set_query_vector(query, data, size),
);

@ffi.Native<
  ffi.UnsignedInt Function(ffi.Pointer<zvec_vector_query_t>, ffi.Int)
>(symbol: 'zvec_vector_query_set_topk')
external int _zvec_vector_query_set_topk(
  ffi.Pointer<zvec_vector_query_t> query,
  int topk,
);

zvec_error_code_t zvec_vector_query_set_topk(
  ffi.Pointer<zvec_vector_query_t> query,
  int topk,
) => zvec_error_code_t.fromValue(_zvec_vector_query_set_topk(query, topk));

final class zvec_collection_options_t extends ffi.Opaque {}

final class zvec_collection_schema_t extends ffi.Opaque {}

final class zvec_collection_t extends ffi.Opaque {}

final class zvec_config_data_t extends ffi.Opaque {}

final class zvec_doc_t extends ffi.Opaque {}

enum zvec_error_code_t {
  ZVEC_OK(0),
  ZVEC_ERROR_NOT_FOUND(1),
  ZVEC_ERROR_ALREADY_EXISTS(2),
  ZVEC_ERROR_INVALID_ARGUMENT(3),
  ZVEC_ERROR_PERMISSION_DENIED(4),
  ZVEC_ERROR_FAILED_PRECONDITION(5),
  ZVEC_ERROR_RESOURCE_EXHAUSTED(6),
  ZVEC_ERROR_UNAVAILABLE(7),
  ZVEC_ERROR_INTERNAL_ERROR(8),
  ZVEC_ERROR_NOT_SUPPORTED(9),
  ZVEC_ERROR_UNKNOWN(10);

  final int value;
  const zvec_error_code_t(this.value);

  static zvec_error_code_t fromValue(int value) => switch (value) {
    0 => ZVEC_OK,
    1 => ZVEC_ERROR_NOT_FOUND,
    2 => ZVEC_ERROR_ALREADY_EXISTS,
    3 => ZVEC_ERROR_INVALID_ARGUMENT,
    4 => ZVEC_ERROR_PERMISSION_DENIED,
    5 => ZVEC_ERROR_FAILED_PRECONDITION,
    6 => ZVEC_ERROR_RESOURCE_EXHAUSTED,
    7 => ZVEC_ERROR_UNAVAILABLE,
    8 => ZVEC_ERROR_INTERNAL_ERROR,
    9 => ZVEC_ERROR_NOT_SUPPORTED,
    10 => ZVEC_ERROR_UNKNOWN,
    _ => throw ArgumentError('Unknown value for zvec_error_code_t: $value'),
  };
}

final class zvec_field_schema_t extends ffi.Opaque {}

final class zvec_index_params_t extends ffi.Opaque {}

final class zvec_vector_query_t extends ffi.Opaque {}
